version: '3.8'
services:
  app:
    environment:
      - MESSENGER_TRANSPORT_DSN=redis://redis:6379
      - REDIS_CACHE_URL=redis://redis:6379
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./app:/var/www/

  redis:
    image: "redis:alpine"
    command: redis-server --maxmemory 2gb --maxmemory-policy noeviction
    container_name: redis
    ports:
      - "6379:6379"
